### ISSUE TITLE
How can i install voice other than en-US?

### ISSUE THREAD

**Issue by bheeshmpita** [evuraan/mintPiper#1]
The default one is en-US while i was looking for British english.

**Comment by evuraan** [comment]
Try with the https://github.com/evuraan/mintPiper/tree/april_2024 branch 

Clone as:
```bash
$ git clone https://github.com/evuraan/mintPiper.git -b april_2024 
```
```bash
$ ./setup.sh 
Setup mintPiper, usage:

	Show available voices:
	./setup.sh -showVoices

	Install:
	./setup.sh <foldername> <arch> <voiceToUse (optional, default: en_US-amy-low)>

	Supported archs: amd64|arm64|armv7
```

See available voices and install one:

```bash
$ ./setup.sh -showVoices |grep GB
    20	en_GB-alan-low
    21	en_GB-alan-medium
    22	en_GB-alba-medium
    23	en_GB-aru-medium
    24	en_GB-cori-medium
    25	en_GB-cori-high
    26	en_GB-jenny_dioco-medium
    27	en_GB-northern_english_male-medium
    28	en_GB-semaine-medium
    29	en_GB-southern_english_female-low
    30	en_GB-vctk-medium


$ ./setup.sh /data/someFolder amd64 en_GB-alan-low 
```

**Comment by bheeshmpita** [comment]
Thanks @evuraan , 2 follow up queries

1. there are about 109 voices listed in `en_GB-vctk-medium` at [https://piper.ttstool.com/](url) How to select among them say voice no. p232
2. Is it possible to configure speech rate too?

**Comment by evuraan** [comment]
1. I've updated the script to support all the [voices piper project ](https://github.com/rhasspy/piper/blob/master/VOICES.md) provides. Beyond that, you will need to download the model and configs of the voices.

3. I currently don't have resources to support non-[core](https://github.com/rhasspy/piper#usage) features . 

 You have to figure things out yourself. Feel free to send in a PR if you do,  Good luck!
